title = "Default Draw.pyo Shapes"

# These are the default shapes as defined in the Basic pane of the Draw.io interface

[default]
base_str = ""
html = 1
white_space = "wrap"
rounded = 0

[rectangle]
inherit = "default"

[rounded_rectangle]
inherit = "default"
rounded = 1

[text]
inherit = "default"
size = [60, 20]
base_str = "text"

[ellipse]
inherit = "default"
size = [120, 80]
base_str = "ellipse"

[square]
inherit = "default"
size = [80, 80]
aspect = "fixed"

[circle]
inherit = "default"
size = [80, 80]
base_str = "ellipse"
aspect = "fixed"

[process]
inherit = "default"
shape = "process"
backgroundOutline = 1

[diamond]
inherit = "default"
size = [80, 80]
base_str = "rhombus"

[parallelogram]
inherit = "default"
shape = "parallelogram"
perimeter = "parelleogramPerimeter"
fixedSize = 1

[hexagon]
inherit = "default"
size = [120, 80]
shape = "hexagon"
perimeter = "hexagonPerimeter2"
fixedSize = 1

[triangle]
inherit = "default"
size = [60, 80]
base_str = "triangle"

[cylinder]
inherit = "default"
size = [60, 80]
shape = "cylinder3"
boundedLbl = 1
backgroundOutline = 1

[cloud]
inherit = "default"
size = [60, 80]
base_str = "ellipse"
shape = "cloud"

[document]
inherit = "default"
size = [120, 80]
shape = "document"
boundedLbl = 1

[internal_storage]
inherit = "default"
size = [80, 80]
shape = "internalStorage"
backgroundOutline = 1

[cube]
inherit = "default"
size = [120, 80]
shape = "cube"
boundedLbl = 1
backgroundOutline = 1
darkOpacity = 0.05
darkOpacity2 = 0.1

[step]
inherit = "default"
size = [120, 80]
shape = "step"
perimeter = "stepPerimeter"

[trapezoid]
inherit = "default"
shape = "trapezoid"
perimeter = "trapezoidPerimeter"

[tape]
inherit = "default"
size = [120, 100]
shape = "tape"

[note]
inherit = "default"
size = [80, 100]
shape = "note"
backgroundOutline = 1
darkOpacity = 0.05

[card]
inherit = "default"
size = [80, 100]
shape = "card"

[callout]
inherit = "default"
size = [120, 80]
shape = "callout"
perimeter = "calloutPerimeter"

[actor]
inherit = "default"
size = [30, 60]
shape = "umlActor"
verticalLabelPosition = "bottom"
verticalAlign = "top"
outlineConnect = 0

[or]
inherit = "default"
size = [60, 80]
shape = "xor"

[and]
inherit = "default"
size = [60, 80]
shape = "or"

[data_storage]
inherit = "default"
size = [100, 80]
shape = "dataStorage"
fixedSize = 1

[container]
inherit = "default"
size = [200, 200]
base_str = "swimlane"
startSize = 0

[labeled_container]
inherit = "default"
size = [200, 200]
base_str = "swimlane"

[labeled_horizontal_container]
inherit = "default"
size = [200, 200]
base_str = "swimlane"
horizontal = 0